version: '3.3'

services:
  database:
    image: postgres:14.5
    hostname: database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/1-init.sql:ro
      - ./db-volume:/var/lib/postgresql/data:rw

  backend:
    build: backend/.
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - ./config.json:/etc/config.json:ro
